icon: fa-shopping-bag
title: Natural Product Line
description: >-
  Excellent foundation for premium sugar wax pastes, aftercare products, and
  tools for Brazilian sugaring.
highlight: DTC brand + subscription potential
order: 4
